apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-deployment
  namespace: OnlineEventBookingMuhammadTaha
  labels:
    app: Booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Booking
  template:
    metadata:
      labels:
        app: Booking
    spec:
      containers:
      - name: Booking
        image: Booking:latest
        ports:
        - containerPort: 5002
        env:
          - name: PORT
            value: "5002"
          - name: DATABASE_URL
            value: "postgres://postgres:Pass123@postgres:5432/devops"
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: OnlineEventBookingMuhammadTaha
spec:
  selector:
    app: Booking
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
