apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: OnlineEventBookingMuhammadTaha
  labels:
    app: Users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Users
  template:
    metadata:
      labels:
        app: Users
    spec:
      containers:
      - name: Users
        image: Users:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: DATABASE_URL
            value: "postgres://postgres:Pass123@postgres:5432/devops"
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: OnlineEventBookingMuhammadTaha
spec:
  selector:
    app: Users
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
