apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  namespace: OnlineEventBookingMuhammadTaha
  labels:
    app: Notifications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Notifications
  template:
    metadata:
      labels:
        app: Notifications
    spec:
      containers:
      - name: Notifications
        image: Notifications:latest
        ports:
        - containerPort: 5003
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DB_PASSWORD
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: RABBITMQ_HOST
          - name: RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: RABBITMQ_PORT

        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: OnlineEventBookingMuhammadTaha
spec:
  selector:
    app: Notifications
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP
